application: hybelrentmap
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- deferred: on
- remote_api: on

handlers:
#- url: /remote_api
#  script: $PYTHON_LIB/google_appengine/google/appengine/ext/remote_api/handler.py
#  login: admin
  #script: /home/emh/google_appengine/google/appengine/ext/remote_api/handler.py
  #login: admin

- url: /static
  static_dir: static

- url: /.*
  script: url_handler.py

